services:
  ###> Database MySQL ###
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: entraide
      MYSQL_USER: entraide_user
      MYSQL_PASSWORD: mysql_password
      MYSQL_ROOT_PASSWORD: root_password
      TZ: Europe/Paris
      MYSQL_DEFAULT_TIME_ZONE: '+02:00'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "database", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 5

  ###> Mercure ###
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      MERCURE_PUBLISHER_JWT_KEY: '2wNmumEkpOoIN8+MYGowxlAZrjg5QfMDo2x25pt5hvw='
      MERCURE_SUBSCRIBER_JWT_KEY: '2wNmumEkpOoIN8+MYGowxlAZrjg5QfMDo2x25pt5hvw='
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://127.0.0.1:8000
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "3000:80"
    volumes:
      - mercure_data:/data
      - mercure_config:/config

  ###> phpMyAdmin ###
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: root_password
    depends_on:
      database:
        condition: service_healthy

  ###> Mailpit ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  php:
    build:
      context: .
      dockerfile: Dockerfile
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/var/www/html:cached
      - ./var:/var/www/html/var
    environment:
      - DATABASE_URL=mysql://entraide_user:mysql_password@database:3306/entraide?serverVersion=8.0
      - MERCURE_URL=http://mercure/.well-known/mercure
      - APP_ENV=dev
    depends_on:
      - database
      - mercure
      - mailer
    ports:
      - "8001:8000"

volumes:
  mysql_data:
  mercure_data:
  mercure_config: